version: '3.1'

services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php-server
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./html:/var/www/html
      - ./config:/usr/local/etc/php
volumes:
  html: {}
  config: {}
# docker cp php-server:/usr/local/etc/php ./config // para copiar los ini a host y editar en el volumen local
